server:
  port: 8080

spring:
  application:
    name: springboot-ai-poc

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta
    model: gemini-2.5-flash
    max-tokens: 4000
    temperature: 0.7

logging:
  level:
    '[com.example.aipoc]': DEBUG
    '[org.springframework.web]': INFO